# Site settings
title: Hello World!
email: shirunjie # shi run jie . me
description: > # this means to ignore newlines until "baseurl:"
  This is a website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.shirunjie.me" # the base hostname & protocol for your site
twitter_username: shirj23
github_username:  shirj

# Build settings
markdown: kramdown
